### PR TITLE
Added UTM, MGRS, GARS, LatLon graticules and coordinate converters

### LINKED ISSUE #11: Port graticule layers and coordinate converters from WorldWindJava
UTM, MGRS, LatLon and GARS graticule layers and UTM, UPS, MGRS coordinates converters can be ported from WorldWindJava.

I will make pull request later.

### PR DESCRIPTION
**Pull request by EMaksymenko**
### Description of the Change
Added UTM, UPS, MGRS coordinates converters and UTM, MGRS, GARS, LatLon graticules.  The code was ported from the WorldWindJava SDK.

### Why Should This Be In Core?
Graticules extend the usefulness of the SDK. 

### Benefits
When displayed, graticules can enhance the geospatial situational awareness. 

### Potential Drawbacks
Unknown.

### Applicable Issues
Closes #11

### CODE REVIEW

**Comment by emxsys** [comment]
@Sufaev Thanks for this pull request.  I updated the description and title to conform to the SDK standards.  Please review it to ensure it is correct; embellish as you see fit.

Looks good. Are you already using this code in production?  If so, I will approve and merge.

**Comment by EMaksymenko** [comment]
@emxsys I have not used this feature in production yet. It was done only month ago. But I spent about three days to test all types of graticule in all level of details. I think it will be better if someone else try to test them also and confirm quality.

Furthermore, I have not tested performance on low-end devices. I have no low-end devices to test. It will be good if somebody confirm that performance is good enough.

But from other hand, you can merge it and we will fix it if something will go wrong. It is not a main functionality and it will not influence main code stability.

**Comment by wcmatthysen** [comment]
@Sufaev, I ported the fixes from the WorldWindJava code-base. However, I cannot commit to this pull-request as I don't have write-access to this repository. You can get the patch I made to this pull-request if you go to this [gist](https://gist.github.com/wcmatthysen/21100b37b7aa2e473f1274f2afd84623). You just need to view the raw file contents by clicking on the "Raw" button and then saving the text to disk as:

    0001-Ported-MGRS-fixes-from-WorldWindJava.patch

And then on this `feature/graticule` branch you do a:

    git am 0001-Ported-MGRS-fixes-from-WorldWindJava.patch

to apply the patch to your branch. You can then push the changes to your fork.

**Comment by EMaksymenko** [comment]
I am receiving an error:

git am ~/0001-Ported-MGRS-fixes-from-WorldWindJava.patch
Applying: Ported MGRS-fixes from WorldWindJava.
.git/rebase-apply/patch:354: trailing whitespace.
.git/rebase-apply/patch:368: trailing whitespace.
.git/rebase-apply/patch:378: trailing whitespace.
.git/rebase-apply/patch:398: trailing whitespace.
.git/rebase-apply/patch:403: trailing whitespace.
error: patch error: worldwind/src/main/java/gov/nasa/worldwind/geom/coords/MGRSCoordConverter.java:33
error: worldwind/src/main/java/gov/nasa/worldwind/geom/coords/MGRSCoordConverter.java: patch can not be applied

**Comment by wcmatthysen** [comment]
@Sufaev, maybe try:

    git am --ignore-whitespace 0001-Ported-MGRS-fixes-from-WorldWindJava.patch

It looks like whitespace errors.

**Comment by EMaksymenko** [comment]
Done. Patch applied. Thanks.

**Pull request merged**
